name: schedule-test

on:
  schedule:
    - cron: '7,32,47,58 * * * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "schedule triggered"
          date -u